// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: srv-common.proto

package com.ice.ssc.srv;

public final class SrvComm {
  private SrvComm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NeAuthReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NeAuthReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *网元.
     * </pre>
     *
     * <code>optional string ne = 1;</code>
     */
    java.lang.String getNe();
    /**
     * <pre>
     *网元.
     * </pre>
     *
     * <code>optional string ne = 1;</code>
     */
    com.google.protobuf.ByteString
        getNeBytes();

    /**
     * <pre>
     *用户名.
     * </pre>
     *
     * <code>optional string usr = 2;</code>
     */
    java.lang.String getUsr();
    /**
     * <pre>
     *用户名.
     * </pre>
     *
     * <code>optional string usr = 2;</code>
     */
    com.google.protobuf.ByteString
        getUsrBytes();

    /**
     * <pre>
     *盐值.
     * </pre>
     *
     * <code>optional string salt = 3;</code>
     */
    java.lang.String getSalt();
    /**
     * <pre>
     *盐值.
     * </pre>
     *
     * <code>optional string salt = 3;</code>
     */
    com.google.protobuf.ByteString
        getSaltBytes();

    /**
     * <pre>
     *SHA512(ne + usr + salt + pwd).
     * </pre>
     *
     * <code>optional string secret = 4;</code>
     */
    java.lang.String getSecret();
    /**
     * <pre>
     *SHA512(ne + usr + salt + pwd).
     * </pre>
     *
     * <code>optional string secret = 4;</code>
     */
    com.google.protobuf.ByteString
        getSecretBytes();
  }
  /**
   * <pre>
   *网元鉴权请求.
   * </pre>
   *
   * Protobuf type {@code NeAuthReq}
   */
  public  static final class NeAuthReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NeAuthReq)
      NeAuthReqOrBuilder {
    // Use NeAuthReq.newBuilder() to construct.
    private NeAuthReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NeAuthReq() {
      ne_ = "";
      usr_ = "";
      salt_ = "";
      secret_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private NeAuthReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              ne_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              usr_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              salt_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              secret_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ice.ssc.srv.SrvComm.internal_static_NeAuthReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ice.ssc.srv.SrvComm.internal_static_NeAuthReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ice.ssc.srv.SrvComm.NeAuthReq.class, com.ice.ssc.srv.SrvComm.NeAuthReq.Builder.class);
    }

    public static final int NE_FIELD_NUMBER = 1;
    private volatile java.lang.Object ne_;
    /**
     * <pre>
     *网元.
     * </pre>
     *
     * <code>optional string ne = 1;</code>
     */
    public java.lang.String getNe() {
      java.lang.Object ref = ne_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ne_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *网元.
     * </pre>
     *
     * <code>optional string ne = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNeBytes() {
      java.lang.Object ref = ne_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ne_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USR_FIELD_NUMBER = 2;
    private volatile java.lang.Object usr_;
    /**
     * <pre>
     *用户名.
     * </pre>
     *
     * <code>optional string usr = 2;</code>
     */
    public java.lang.String getUsr() {
      java.lang.Object ref = usr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        usr_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户名.
     * </pre>
     *
     * <code>optional string usr = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsrBytes() {
      java.lang.Object ref = usr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        usr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SALT_FIELD_NUMBER = 3;
    private volatile java.lang.Object salt_;
    /**
     * <pre>
     *盐值.
     * </pre>
     *
     * <code>optional string salt = 3;</code>
     */
    public java.lang.String getSalt() {
      java.lang.Object ref = salt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        salt_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *盐值.
     * </pre>
     *
     * <code>optional string salt = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSaltBytes() {
      java.lang.Object ref = salt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        salt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SECRET_FIELD_NUMBER = 4;
    private volatile java.lang.Object secret_;
    /**
     * <pre>
     *SHA512(ne + usr + salt + pwd).
     * </pre>
     *
     * <code>optional string secret = 4;</code>
     */
    public java.lang.String getSecret() {
      java.lang.Object ref = secret_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        secret_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *SHA512(ne + usr + salt + pwd).
     * </pre>
     *
     * <code>optional string secret = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSecretBytes() {
      java.lang.Object ref = secret_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ne_);
      }
      if (!getUsrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, usr_);
      }
      if (!getSaltBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, salt_);
      }
      if (!getSecretBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, secret_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ne_);
      }
      if (!getUsrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, usr_);
      }
      if (!getSaltBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, salt_);
      }
      if (!getSecretBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, secret_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ice.ssc.srv.SrvComm.NeAuthReq)) {
        return super.equals(obj);
      }
      com.ice.ssc.srv.SrvComm.NeAuthReq other = (com.ice.ssc.srv.SrvComm.NeAuthReq) obj;

      boolean result = true;
      result = result && getNe()
          .equals(other.getNe());
      result = result && getUsr()
          .equals(other.getUsr());
      result = result && getSalt()
          .equals(other.getSalt());
      result = result && getSecret()
          .equals(other.getSecret());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NE_FIELD_NUMBER;
      hash = (53 * hash) + getNe().hashCode();
      hash = (37 * hash) + USR_FIELD_NUMBER;
      hash = (53 * hash) + getUsr().hashCode();
      hash = (37 * hash) + SALT_FIELD_NUMBER;
      hash = (53 * hash) + getSalt().hashCode();
      hash = (37 * hash) + SECRET_FIELD_NUMBER;
      hash = (53 * hash) + getSecret().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ice.ssc.srv.SrvComm.NeAuthReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ice.ssc.srv.SrvComm.NeAuthReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ice.ssc.srv.SrvComm.NeAuthReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ice.ssc.srv.SrvComm.NeAuthReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ice.ssc.srv.SrvComm.NeAuthReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ice.ssc.srv.SrvComm.NeAuthReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ice.ssc.srv.SrvComm.NeAuthReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ice.ssc.srv.SrvComm.NeAuthReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ice.ssc.srv.SrvComm.NeAuthReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ice.ssc.srv.SrvComm.NeAuthReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ice.ssc.srv.SrvComm.NeAuthReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *网元鉴权请求.
     * </pre>
     *
     * Protobuf type {@code NeAuthReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NeAuthReq)
        com.ice.ssc.srv.SrvComm.NeAuthReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ice.ssc.srv.SrvComm.internal_static_NeAuthReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ice.ssc.srv.SrvComm.internal_static_NeAuthReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ice.ssc.srv.SrvComm.NeAuthReq.class, com.ice.ssc.srv.SrvComm.NeAuthReq.Builder.class);
      }

      // Construct using com.ice.ssc.srv.SrvComm.NeAuthReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ne_ = "";

        usr_ = "";

        salt_ = "";

        secret_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ice.ssc.srv.SrvComm.internal_static_NeAuthReq_descriptor;
      }

      public com.ice.ssc.srv.SrvComm.NeAuthReq getDefaultInstanceForType() {
        return com.ice.ssc.srv.SrvComm.NeAuthReq.getDefaultInstance();
      }

      public com.ice.ssc.srv.SrvComm.NeAuthReq build() {
        com.ice.ssc.srv.SrvComm.NeAuthReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ice.ssc.srv.SrvComm.NeAuthReq buildPartial() {
        com.ice.ssc.srv.SrvComm.NeAuthReq result = new com.ice.ssc.srv.SrvComm.NeAuthReq(this);
        result.ne_ = ne_;
        result.usr_ = usr_;
        result.salt_ = salt_;
        result.secret_ = secret_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ice.ssc.srv.SrvComm.NeAuthReq) {
          return mergeFrom((com.ice.ssc.srv.SrvComm.NeAuthReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ice.ssc.srv.SrvComm.NeAuthReq other) {
        if (other == com.ice.ssc.srv.SrvComm.NeAuthReq.getDefaultInstance()) return this;
        if (!other.getNe().isEmpty()) {
          ne_ = other.ne_;
          onChanged();
        }
        if (!other.getUsr().isEmpty()) {
          usr_ = other.usr_;
          onChanged();
        }
        if (!other.getSalt().isEmpty()) {
          salt_ = other.salt_;
          onChanged();
        }
        if (!other.getSecret().isEmpty()) {
          secret_ = other.secret_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ice.ssc.srv.SrvComm.NeAuthReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ice.ssc.srv.SrvComm.NeAuthReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object ne_ = "";
      /**
       * <pre>
       *网元.
       * </pre>
       *
       * <code>optional string ne = 1;</code>
       */
      public java.lang.String getNe() {
        java.lang.Object ref = ne_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ne_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *网元.
       * </pre>
       *
       * <code>optional string ne = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNeBytes() {
        java.lang.Object ref = ne_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ne_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *网元.
       * </pre>
       *
       * <code>optional string ne = 1;</code>
       */
      public Builder setNe(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ne_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *网元.
       * </pre>
       *
       * <code>optional string ne = 1;</code>
       */
      public Builder clearNe() {
        
        ne_ = getDefaultInstance().getNe();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *网元.
       * </pre>
       *
       * <code>optional string ne = 1;</code>
       */
      public Builder setNeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ne_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object usr_ = "";
      /**
       * <pre>
       *用户名.
       * </pre>
       *
       * <code>optional string usr = 2;</code>
       */
      public java.lang.String getUsr() {
        java.lang.Object ref = usr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          usr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户名.
       * </pre>
       *
       * <code>optional string usr = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUsrBytes() {
        java.lang.Object ref = usr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          usr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户名.
       * </pre>
       *
       * <code>optional string usr = 2;</code>
       */
      public Builder setUsr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        usr_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名.
       * </pre>
       *
       * <code>optional string usr = 2;</code>
       */
      public Builder clearUsr() {
        
        usr_ = getDefaultInstance().getUsr();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名.
       * </pre>
       *
       * <code>optional string usr = 2;</code>
       */
      public Builder setUsrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        usr_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object salt_ = "";
      /**
       * <pre>
       *盐值.
       * </pre>
       *
       * <code>optional string salt = 3;</code>
       */
      public java.lang.String getSalt() {
        java.lang.Object ref = salt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          salt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *盐值.
       * </pre>
       *
       * <code>optional string salt = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSaltBytes() {
        java.lang.Object ref = salt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          salt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *盐值.
       * </pre>
       *
       * <code>optional string salt = 3;</code>
       */
      public Builder setSalt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        salt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *盐值.
       * </pre>
       *
       * <code>optional string salt = 3;</code>
       */
      public Builder clearSalt() {
        
        salt_ = getDefaultInstance().getSalt();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *盐值.
       * </pre>
       *
       * <code>optional string salt = 3;</code>
       */
      public Builder setSaltBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        salt_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object secret_ = "";
      /**
       * <pre>
       *SHA512(ne + usr + salt + pwd).
       * </pre>
       *
       * <code>optional string secret = 4;</code>
       */
      public java.lang.String getSecret() {
        java.lang.Object ref = secret_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          secret_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *SHA512(ne + usr + salt + pwd).
       * </pre>
       *
       * <code>optional string secret = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSecretBytes() {
        java.lang.Object ref = secret_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          secret_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *SHA512(ne + usr + salt + pwd).
       * </pre>
       *
       * <code>optional string secret = 4;</code>
       */
      public Builder setSecret(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        secret_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *SHA512(ne + usr + salt + pwd).
       * </pre>
       *
       * <code>optional string secret = 4;</code>
       */
      public Builder clearSecret() {
        
        secret_ = getDefaultInstance().getSecret();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *SHA512(ne + usr + salt + pwd).
       * </pre>
       *
       * <code>optional string secret = 4;</code>
       */
      public Builder setSecretBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        secret_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:NeAuthReq)
    }

    // @@protoc_insertion_point(class_scope:NeAuthReq)
    private static final com.ice.ssc.srv.SrvComm.NeAuthReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ice.ssc.srv.SrvComm.NeAuthReq();
    }

    public static com.ice.ssc.srv.SrvComm.NeAuthReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NeAuthReq>
        PARSER = new com.google.protobuf.AbstractParser<NeAuthReq>() {
      public NeAuthReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NeAuthReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NeAuthReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NeAuthReq> getParserForType() {
      return PARSER;
    }

    public com.ice.ssc.srv.SrvComm.NeAuthReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NeAuthRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NeAuthRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *鉴权通过后的网元标识(NE&#64;USR&#64;ID)
     * </pre>
     *
     * <code>optional string neaddr = 1;</code>
     */
    java.lang.String getNeaddr();
    /**
     * <pre>
     *鉴权通过后的网元标识(NE&#64;USR&#64;ID)
     * </pre>
     *
     * <code>optional string neaddr = 1;</code>
     */
    com.google.protobuf.ByteString
        getNeaddrBytes();

    /**
     * <pre>
     *令牌.
     * </pre>
     *
     * <code>optional string token = 2;</code>
     */
    java.lang.String getToken();
    /**
     * <pre>
     *令牌.
     * </pre>
     *
     * <code>optional string token = 2;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code NeAuthRsp}
   */
  public  static final class NeAuthRsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NeAuthRsp)
      NeAuthRspOrBuilder {
    // Use NeAuthRsp.newBuilder() to construct.
    private NeAuthRsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NeAuthRsp() {
      neaddr_ = "";
      token_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private NeAuthRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              neaddr_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ice.ssc.srv.SrvComm.internal_static_NeAuthRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ice.ssc.srv.SrvComm.internal_static_NeAuthRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ice.ssc.srv.SrvComm.NeAuthRsp.class, com.ice.ssc.srv.SrvComm.NeAuthRsp.Builder.class);
    }

    public static final int NEADDR_FIELD_NUMBER = 1;
    private volatile java.lang.Object neaddr_;
    /**
     * <pre>
     *鉴权通过后的网元标识(NE&#64;USR&#64;ID)
     * </pre>
     *
     * <code>optional string neaddr = 1;</code>
     */
    public java.lang.String getNeaddr() {
      java.lang.Object ref = neaddr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        neaddr_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *鉴权通过后的网元标识(NE&#64;USR&#64;ID)
     * </pre>
     *
     * <code>optional string neaddr = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNeaddrBytes() {
      java.lang.Object ref = neaddr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        neaddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object token_;
    /**
     * <pre>
     *令牌.
     * </pre>
     *
     * <code>optional string token = 2;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *令牌.
     * </pre>
     *
     * <code>optional string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNeaddrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, neaddr_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNeaddrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, neaddr_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ice.ssc.srv.SrvComm.NeAuthRsp)) {
        return super.equals(obj);
      }
      com.ice.ssc.srv.SrvComm.NeAuthRsp other = (com.ice.ssc.srv.SrvComm.NeAuthRsp) obj;

      boolean result = true;
      result = result && getNeaddr()
          .equals(other.getNeaddr());
      result = result && getToken()
          .equals(other.getToken());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NEADDR_FIELD_NUMBER;
      hash = (53 * hash) + getNeaddr().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ice.ssc.srv.SrvComm.NeAuthRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ice.ssc.srv.SrvComm.NeAuthRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ice.ssc.srv.SrvComm.NeAuthRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ice.ssc.srv.SrvComm.NeAuthRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ice.ssc.srv.SrvComm.NeAuthRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ice.ssc.srv.SrvComm.NeAuthRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ice.ssc.srv.SrvComm.NeAuthRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ice.ssc.srv.SrvComm.NeAuthRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ice.ssc.srv.SrvComm.NeAuthRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ice.ssc.srv.SrvComm.NeAuthRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ice.ssc.srv.SrvComm.NeAuthRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NeAuthRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NeAuthRsp)
        com.ice.ssc.srv.SrvComm.NeAuthRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ice.ssc.srv.SrvComm.internal_static_NeAuthRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ice.ssc.srv.SrvComm.internal_static_NeAuthRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ice.ssc.srv.SrvComm.NeAuthRsp.class, com.ice.ssc.srv.SrvComm.NeAuthRsp.Builder.class);
      }

      // Construct using com.ice.ssc.srv.SrvComm.NeAuthRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        neaddr_ = "";

        token_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ice.ssc.srv.SrvComm.internal_static_NeAuthRsp_descriptor;
      }

      public com.ice.ssc.srv.SrvComm.NeAuthRsp getDefaultInstanceForType() {
        return com.ice.ssc.srv.SrvComm.NeAuthRsp.getDefaultInstance();
      }

      public com.ice.ssc.srv.SrvComm.NeAuthRsp build() {
        com.ice.ssc.srv.SrvComm.NeAuthRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ice.ssc.srv.SrvComm.NeAuthRsp buildPartial() {
        com.ice.ssc.srv.SrvComm.NeAuthRsp result = new com.ice.ssc.srv.SrvComm.NeAuthRsp(this);
        result.neaddr_ = neaddr_;
        result.token_ = token_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ice.ssc.srv.SrvComm.NeAuthRsp) {
          return mergeFrom((com.ice.ssc.srv.SrvComm.NeAuthRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ice.ssc.srv.SrvComm.NeAuthRsp other) {
        if (other == com.ice.ssc.srv.SrvComm.NeAuthRsp.getDefaultInstance()) return this;
        if (!other.getNeaddr().isEmpty()) {
          neaddr_ = other.neaddr_;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ice.ssc.srv.SrvComm.NeAuthRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ice.ssc.srv.SrvComm.NeAuthRsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object neaddr_ = "";
      /**
       * <pre>
       *鉴权通过后的网元标识(NE&#64;USR&#64;ID)
       * </pre>
       *
       * <code>optional string neaddr = 1;</code>
       */
      public java.lang.String getNeaddr() {
        java.lang.Object ref = neaddr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          neaddr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *鉴权通过后的网元标识(NE&#64;USR&#64;ID)
       * </pre>
       *
       * <code>optional string neaddr = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNeaddrBytes() {
        java.lang.Object ref = neaddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          neaddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *鉴权通过后的网元标识(NE&#64;USR&#64;ID)
       * </pre>
       *
       * <code>optional string neaddr = 1;</code>
       */
      public Builder setNeaddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        neaddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *鉴权通过后的网元标识(NE&#64;USR&#64;ID)
       * </pre>
       *
       * <code>optional string neaddr = 1;</code>
       */
      public Builder clearNeaddr() {
        
        neaddr_ = getDefaultInstance().getNeaddr();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *鉴权通过后的网元标识(NE&#64;USR&#64;ID)
       * </pre>
       *
       * <code>optional string neaddr = 1;</code>
       */
      public Builder setNeaddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        neaddr_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <pre>
       *令牌.
       * </pre>
       *
       * <code>optional string token = 2;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *令牌.
       * </pre>
       *
       * <code>optional string token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *令牌.
       * </pre>
       *
       * <code>optional string token = 2;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *令牌.
       * </pre>
       *
       * <code>optional string token = 2;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *令牌.
       * </pre>
       *
       * <code>optional string token = 2;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:NeAuthRsp)
    }

    // @@protoc_insertion_point(class_scope:NeAuthRsp)
    private static final com.ice.ssc.srv.SrvComm.NeAuthRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ice.ssc.srv.SrvComm.NeAuthRsp();
    }

    public static com.ice.ssc.srv.SrvComm.NeAuthRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NeAuthRsp>
        PARSER = new com.google.protobuf.AbstractParser<NeAuthRsp>() {
      public NeAuthRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NeAuthRsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NeAuthRsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NeAuthRsp> getParserForType() {
      return PARSER;
    }

    public com.ice.ssc.srv.SrvComm.NeAuthRsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NeStatusChangeReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NeStatusChangeReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *网元.
     * </pre>
     *
     * <code>optional string ne = 1;</code>
     */
    java.lang.String getNe();
    /**
     * <pre>
     *网元.
     * </pre>
     *
     * <code>optional string ne = 1;</code>
     */
    com.google.protobuf.ByteString
        getNeBytes();

    /**
     * <pre>
     *true: establish, false: disconnect.
     * </pre>
     *
     * <code>optional bool status = 2;</code>
     */
    boolean getStatus();
  }
  /**
   * <pre>
   *网元状态改变.
   * </pre>
   *
   * Protobuf type {@code NeStatusChangeReq}
   */
  public  static final class NeStatusChangeReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NeStatusChangeReq)
      NeStatusChangeReqOrBuilder {
    // Use NeStatusChangeReq.newBuilder() to construct.
    private NeStatusChangeReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NeStatusChangeReq() {
      ne_ = "";
      status_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private NeStatusChangeReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              ne_ = s;
              break;
            }
            case 16: {

              status_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ice.ssc.srv.SrvComm.internal_static_NeStatusChangeReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ice.ssc.srv.SrvComm.internal_static_NeStatusChangeReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ice.ssc.srv.SrvComm.NeStatusChangeReq.class, com.ice.ssc.srv.SrvComm.NeStatusChangeReq.Builder.class);
    }

    public static final int NE_FIELD_NUMBER = 1;
    private volatile java.lang.Object ne_;
    /**
     * <pre>
     *网元.
     * </pre>
     *
     * <code>optional string ne = 1;</code>
     */
    public java.lang.String getNe() {
      java.lang.Object ref = ne_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ne_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *网元.
     * </pre>
     *
     * <code>optional string ne = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNeBytes() {
      java.lang.Object ref = ne_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ne_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private boolean status_;
    /**
     * <pre>
     *true: establish, false: disconnect.
     * </pre>
     *
     * <code>optional bool status = 2;</code>
     */
    public boolean getStatus() {
      return status_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ne_);
      }
      if (status_ != false) {
        output.writeBool(2, status_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ne_);
      }
      if (status_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, status_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ice.ssc.srv.SrvComm.NeStatusChangeReq)) {
        return super.equals(obj);
      }
      com.ice.ssc.srv.SrvComm.NeStatusChangeReq other = (com.ice.ssc.srv.SrvComm.NeStatusChangeReq) obj;

      boolean result = true;
      result = result && getNe()
          .equals(other.getNe());
      result = result && (getStatus()
          == other.getStatus());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NE_FIELD_NUMBER;
      hash = (53 * hash) + getNe().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getStatus());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ice.ssc.srv.SrvComm.NeStatusChangeReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ice.ssc.srv.SrvComm.NeStatusChangeReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ice.ssc.srv.SrvComm.NeStatusChangeReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ice.ssc.srv.SrvComm.NeStatusChangeReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ice.ssc.srv.SrvComm.NeStatusChangeReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ice.ssc.srv.SrvComm.NeStatusChangeReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ice.ssc.srv.SrvComm.NeStatusChangeReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ice.ssc.srv.SrvComm.NeStatusChangeReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ice.ssc.srv.SrvComm.NeStatusChangeReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ice.ssc.srv.SrvComm.NeStatusChangeReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ice.ssc.srv.SrvComm.NeStatusChangeReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *网元状态改变.
     * </pre>
     *
     * Protobuf type {@code NeStatusChangeReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NeStatusChangeReq)
        com.ice.ssc.srv.SrvComm.NeStatusChangeReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ice.ssc.srv.SrvComm.internal_static_NeStatusChangeReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ice.ssc.srv.SrvComm.internal_static_NeStatusChangeReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ice.ssc.srv.SrvComm.NeStatusChangeReq.class, com.ice.ssc.srv.SrvComm.NeStatusChangeReq.Builder.class);
      }

      // Construct using com.ice.ssc.srv.SrvComm.NeStatusChangeReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ne_ = "";

        status_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ice.ssc.srv.SrvComm.internal_static_NeStatusChangeReq_descriptor;
      }

      public com.ice.ssc.srv.SrvComm.NeStatusChangeReq getDefaultInstanceForType() {
        return com.ice.ssc.srv.SrvComm.NeStatusChangeReq.getDefaultInstance();
      }

      public com.ice.ssc.srv.SrvComm.NeStatusChangeReq build() {
        com.ice.ssc.srv.SrvComm.NeStatusChangeReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ice.ssc.srv.SrvComm.NeStatusChangeReq buildPartial() {
        com.ice.ssc.srv.SrvComm.NeStatusChangeReq result = new com.ice.ssc.srv.SrvComm.NeStatusChangeReq(this);
        result.ne_ = ne_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ice.ssc.srv.SrvComm.NeStatusChangeReq) {
          return mergeFrom((com.ice.ssc.srv.SrvComm.NeStatusChangeReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ice.ssc.srv.SrvComm.NeStatusChangeReq other) {
        if (other == com.ice.ssc.srv.SrvComm.NeStatusChangeReq.getDefaultInstance()) return this;
        if (!other.getNe().isEmpty()) {
          ne_ = other.ne_;
          onChanged();
        }
        if (other.getStatus() != false) {
          setStatus(other.getStatus());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ice.ssc.srv.SrvComm.NeStatusChangeReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ice.ssc.srv.SrvComm.NeStatusChangeReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object ne_ = "";
      /**
       * <pre>
       *网元.
       * </pre>
       *
       * <code>optional string ne = 1;</code>
       */
      public java.lang.String getNe() {
        java.lang.Object ref = ne_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ne_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *网元.
       * </pre>
       *
       * <code>optional string ne = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNeBytes() {
        java.lang.Object ref = ne_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ne_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *网元.
       * </pre>
       *
       * <code>optional string ne = 1;</code>
       */
      public Builder setNe(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ne_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *网元.
       * </pre>
       *
       * <code>optional string ne = 1;</code>
       */
      public Builder clearNe() {
        
        ne_ = getDefaultInstance().getNe();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *网元.
       * </pre>
       *
       * <code>optional string ne = 1;</code>
       */
      public Builder setNeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ne_ = value;
        onChanged();
        return this;
      }

      private boolean status_ ;
      /**
       * <pre>
       *true: establish, false: disconnect.
       * </pre>
       *
       * <code>optional bool status = 2;</code>
       */
      public boolean getStatus() {
        return status_;
      }
      /**
       * <pre>
       *true: establish, false: disconnect.
       * </pre>
       *
       * <code>optional bool status = 2;</code>
       */
      public Builder setStatus(boolean value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *true: establish, false: disconnect.
       * </pre>
       *
       * <code>optional bool status = 2;</code>
       */
      public Builder clearStatus() {
        
        status_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:NeStatusChangeReq)
    }

    // @@protoc_insertion_point(class_scope:NeStatusChangeReq)
    private static final com.ice.ssc.srv.SrvComm.NeStatusChangeReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ice.ssc.srv.SrvComm.NeStatusChangeReq();
    }

    public static com.ice.ssc.srv.SrvComm.NeStatusChangeReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NeStatusChangeReq>
        PARSER = new com.google.protobuf.AbstractParser<NeStatusChangeReq>() {
      public NeStatusChangeReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NeStatusChangeReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NeStatusChangeReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NeStatusChangeReq> getParserForType() {
      return PARSER;
    }

    public com.ice.ssc.srv.SrvComm.NeStatusChangeReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NeAuthReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NeAuthReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NeAuthRsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NeAuthRsp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NeStatusChangeReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NeStatusChangeReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020srv-common.proto\"B\n\tNeAuthReq\022\n\n\002ne\030\001 " +
      "\001(\t\022\013\n\003usr\030\002 \001(\t\022\014\n\004salt\030\003 \001(\t\022\016\n\006secret" +
      "\030\004 \001(\t\"*\n\tNeAuthRsp\022\016\n\006neaddr\030\001 \001(\t\022\r\n\005t" +
      "oken\030\002 \001(\t\"/\n\021NeStatusChangeReq\022\n\n\002ne\030\001 " +
      "\001(\t\022\016\n\006status\030\002 \001(\010B\032\n\017com.ice.ssc.srvB\007" +
      "SrvCommb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NeAuthReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NeAuthReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NeAuthReq_descriptor,
        new java.lang.String[] { "Ne", "Usr", "Salt", "Secret", });
    internal_static_NeAuthRsp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NeAuthRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NeAuthRsp_descriptor,
        new java.lang.String[] { "Neaddr", "Token", });
    internal_static_NeStatusChangeReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_NeStatusChangeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NeStatusChangeReq_descriptor,
        new java.lang.String[] { "Ne", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
